name: "edit-ours-sd-"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0
 
data_type: "gs-load"
data:
  batch_size: 1
  source: ???
  max_view_num: 96
  eval_camera_distance: 4.0
  camera_distance_range: [1.5, 4.0]
  light_sample_strategy: "dreamfusion3dgs"
  height: 512
  width: 512

  elevation_view_num: 2
  azimuth_view_num: 8
  # elevation_range: [-10 , 80]
system_type: "gsedit-system-edit"
system:
  gs_source: ???
  edit_begin_step: 0
  densify_until_iter: 1501
  densify_from_iter: 100
  densification_interval: 100
  max_densify_percent: 0.01
  max_grad: 5
  min_opacity: 0.005
  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stable-diffusion-v1-5/stable-diffusion-v1-5"
    prompt: 'Turn him into a clown'

  dds_target_prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: 'turn him into a clown'
    
  dds_source_prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: 'a photo of a face'

  seg_prompt: 'a person'

  gs_lr_scaler: 1
  gs_final_lr_scaler: 1
  color_lr_scaler: 1
  opacity_lr_scaler: 1
  scaling_lr_scaler: 1
  rotation_lr_scaler: 1

  second_guidance_type: "stable-diffusion-ssd-guidance"
  second_guidance:
    min_step_percent: 0.02
    max_step_percent: 0.98
    guidance_scale: 7.5   # CFG scale
    enhance_scale: 5.5    # prompt enhancement scale; 5.5 or 7.5
    image_scale: 2.0      # cross-trajectory scale
    diffusion_steps: 1000
    use_dds: true
    use_ssd: true

  loggers:
    wandb:
      enable: false
      project: 'threestudio_gs'
      name: None

  loss:
    lambda_sparsity: 0.0
    lambda_opaque: 0.0
    lambda_l1: 0.0
    lambda_p: 0.0
    lambda_dds: 1.0
    lambda_anchor_color: 0
    lambda_anchor_geo: 5
    lambda_anchor_opacity: 5
    lambda_anchor_scale: 5
    lambda_move: 0
    lambda_alpha: 0
    lambda_scale: 0

  optimizer:
    name: Adam
    args:
      lr: 0.001
      betas: [0.9, 0.99]
      eps: 1.e-15

trainer:
  max_steps: 1500
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 200
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}

# white_background: true